<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[TestA]]>
    </line>
    <line>
      <![CDATA[Status is 1]]>
    </line>
    <line>
      <![CDATA[TestA]]>
    </line>
    <line>
      <![CDATA[TestB]]>
    </line>
    <line>
      <![CDATA[Status is 2]]>
    </line>
    <line>
      <![CDATA[TestB]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="60" started-at="2021-01-27T13:34:28Z" finished-at="2021-01-27T13:34:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="60" started-at="2021-01-27T13:34:28Z" finished-at="2021-01-27T13:34:28Z">
      <class name="basic.Test_Status_MethodName">
        <test-method status="PASS" signature="TestA()[pri:0, instance:basic.Test_Status_MethodName@56f4468b]" name="TestA" duration-ms="15" started-at="2021-01-27T13:34:28Z" finished-at="2021-01-27T13:34:28Z">
          <reporter-output>
            <line>
              <![CDATA[TestA]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestA -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:basic.Test_Status_MethodName@56f4468b]" name="postCondition" is-config="true" duration-ms="2" started-at="2021-01-27T13:34:28Z" finished-at="2021-01-27T13:34:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestA status=SUCCESS method=Test_Status_MethodName.TestA()[pri:0, instance:basic.Test_Status_MethodName@56f4468b] output=TestA]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Status is 1]]>
            </line>
            <line>
              <![CDATA[TestA]]>
            </line>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="FAIL" signature="TestB()[pri:0, instance:basic.Test_Status_MethodName@56f4468b]" name="TestB" duration-ms="4" started-at="2021-01-27T13:34:28Z" finished-at="2021-01-27T13:34:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at basic.Test_Status_MethodName.TestB(Test_Status_MethodName.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TestB]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestB -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:basic.Test_Status_MethodName@56f4468b]" name="postCondition" is-config="true" duration-ms="1" started-at="2021-01-27T13:34:28Z" finished-at="2021-01-27T13:34:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestB status=FAILURE method=Test_Status_MethodName.TestB()[pri:0, instance:basic.Test_Status_MethodName@56f4468b] output=TestB]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Status is 2]]>
            </line>
            <line>
              <![CDATA[TestB]]>
            </line>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- basic.Test_Status_MethodName -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
